-- Additional vocabulary (86 words)
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'でんしゃ', 'densha', 'kereta', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'バス', 'basu', 'bus', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'タクシー', 'takushii', 'taksi', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'くうこう', 'kuukou', 'bandara', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'えき', 'eki', 'stasiun', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'びょういん', 'byouin', 'rumah sakit', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'こうばん', 'kouban', 'pos polisi', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'ぎんこう', 'ginkou', 'bank', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'ゆうびんきょく', 'yuubinkyoku', 'kantor pos', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'としょかん', 'toshokan', 'perpustakaan', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'びじゅつかん', 'bijutsukan', 'museum seni', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'こうえん', 'kouen', 'taman', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'はくぶつかん', 'hakubutsukan', 'museum', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (1, 'おてら', 'otera', 'kuil', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'じんじゃ', 'jinja', 'kuil Shinto', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'コンビニ', 'konbini', 'minimarket', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'スーパー', 'suupaa', 'supermarket', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'やおや', 'yaoya', 'toko sayur', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'さかなや', 'sakanaya', 'toko ikan', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'にくや', 'nikuya', 'toko daging', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'はなや', 'hanaya', 'toko bunga', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'ほんや', 'honya', 'toko buku', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'くすりや', 'kusuriya', 'apotek', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'でぱーと', 'depaato', 'department store', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'せんもんてん', 'senmonten', 'toko khusus', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'あめ', 'ame', 'permen', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'パン', 'pan', 'roti', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (2, 'ぎゅうにゅう', 'gyuunyuu', 'susu', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'くだもの', 'kudamono', 'buah', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'やさい', 'yasai', 'sayur', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'たまご', 'tamago', 'telur', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'さとう', 'satou', 'gula', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'しお', 'shio', 'garam', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'しょうゆ', 'shouyu', 'kecap', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'みそ', 'miso', 'miso', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'ごはん', 'gohan', 'nasi', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'あさごはん', 'asagohan', 'sarapan', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'ひるごはん', 'hirugohan', 'makan siang', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'ばんごはん', 'bangohan', 'makan malam', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'くだもの', 'kudamono', 'buah', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'いぬ', 'inu', 'anjing', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (3, 'ねこ', 'neko', 'kucing', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'とり', 'tori', 'burung', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'うま', 'uma', 'kuda', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'うし', 'ushi', 'sapi', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'ぶた', 'buta', 'babi', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'さかな', 'sakana', 'ikan', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'むし', 'mushi', 'serangga', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'はな', 'hana', 'bunga', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'き', 'ki', 'pohon', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'くさ', 'kusa', 'rumput', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'つち', 'tsuchi', 'tanah', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'そら', 'sora', 'langit', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'くも', 'kumo', 'awan', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'かぜ', 'kaze', 'angin', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (4, 'ゆき', 'yuki', 'salju', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'かみなり', 'kaminari', 'petir', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'にじ', 'niji', 'pelangi', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'あか', 'aka', 'merah', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'あお', 'ao', 'biru', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'きいろ', 'kiiro', 'kuning', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'みどり', 'midori', 'hijau', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'むらさき', 'murasaki', 'ungu', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'ちゃいろ', 'chairo', 'coklat', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'くろ', 'kuro', 'hitam', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'しろ', 'shiro', 'putih', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'はいいろ', 'haiiro', 'abu-abu', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'おおきい', 'ookii', 'besar', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'ちいさい', 'chiisai', 'kecil', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (5, 'あたらしい', 'atarashii', 'baru', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'ふるい', 'furui', 'tua', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'いい', 'ii', 'baik', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'わるい', 'warui', 'buruk', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'あつい', 'atsui', 'panas', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'さむい', 'samui', 'dingin', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'つめたい', 'tsumetai', 'dingin (benda)', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'むずかしい', 'muzukashii', 'susah', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'やさしい', 'yasashii', 'mudah/baik hati', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'おもしろい', 'omoshiroi', 'menarik', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'つまらない', 'tsumaranai', 'membosankan', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'いそがしい', 'isogashii', 'sibuk', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'ひま', 'hima', 'waktu luang', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'げんき', 'genki', 'sehat', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (6, 'しんぱい', 'shinpai', 'khawatir', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (7, 'だいじょうぶ', 'daijoubu', 'tidak apa-apa', NULL) ON CONFLICT DO NOTHING;
INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia, contoh_kalimat) VALUES (7, 'むり', 'muri', 'mustahil', NULL) ON CONFLICT DO NOTHING;