-- ============================================================
-- SEED DATA: Full 50 Lessons Minna no Nihongo
-- ============================================================
INSERT INTO lessons (book, nomor_pelajaran, judul, urutan, is_free) VALUES
  ('I', 1, 'はじめまして (Hajimemashite)', 1, true),
  ('I', 2, 'これからお世話になります (Yoroshiku onegaishimasu)', 2, true),
  ('I', 3, 'これをください (Kore o kudasai)', 3, true),
  ('I', 4, 'そちらは何ですか (Sochira wa nan desu ka)', 4, false),
  ('I', 5, 'ここにあります (Koko ni arimasu)', 5, false),
  ('I', 6, 'いっしょに行きませんか (Issho ni ikimasen ka)', 6, false),
  ('I', 7, '何を勉強しますか (Nani o benkyou shimasu ka)', 7, false),
  ('I', 8, 'もう一度お願いします (Mou ichido onegai shimasu)', 8, false),
  ('I', 9, '少し分かります (Sukoshi wakarimasu)', 9, false),
  ('I', 10, 'あそこにあります (Asoko ni arimasu)', 10, false),
  ('I', 11, 'いくらですか (Ikura desu ka)', 11, false),
  ('I', 12, '私の町はにぎやかです (Watashi no machi wa nigiyaka desu)', 12, false),
  ('I', 13, 'もう予約しましたか (Mou yoyaku shimashita ka)', 13, false),
  ('I', 14, '電車で行きます (Densha de ikimasu)', 14, false),
  ('I', 15, 'どうぞよろしく (Douzo yoroshiku)', 15, false),
  ('I', 16, '使い方を教えてください (Tsukaikata o oshiete kudasai)', 16, false),
  ('I', 17, 'どうしましたか (Dou shimashita ka)', 17, false),
  ('I', 18, '趣味は何ですか (Shumi wa nan desu ka)', 18, false),
  ('I', 19, '体に気をつけてください (Karada ni ki o tsukete kudasai)', 19, false),
  ('I', 20, '夏休みはどうですか (Natsuyasumi wa dou desu ka)', 20, false),
  ('I', 21, '何と言いましたか (Nan to iimashita ka)', 21, false),
  ('I', 22, 'これは便利ですね (Kore wa benri desu ne)', 22, false),
  ('I', 23, '約束を忘れないでください (Yakusoku o wasurenaide kudasai)', 23, false),
  ('I', 24, '手伝ってくれますか (Tetsudatte kuremasu ka)', 24, false),
  ('I', 25, 'どうやって行きますか (Dou yatte ikimasu ka)', 25, false),
  ('II', 26, 'お久しぶりです (Ohisashiburi desu)', 26, false),
  ('II', 27, '伺ってもいいですか (Ukagatte mo ii desu ka)', 27, false),
  ('II', 28, '日本語を教えてくれませんか (Nihongo o oshiete kuremasen ka)', 28, false),
  ('II', 29, '駅まで迎えに行きます (Eki made mukae ni ikimasu)', 29, false),
  ('II', 30, '忘れ物をしました (Wasuremono o shimashita)', 30, false),
  ('II', 31, 'これは便利なアプリです (Kore wa benri na apuri desu)', 31, false),
  ('II', 32, '今住んでいるところはどこですか (Ima sunde iru tokoro wa doko desu ka)', 32, false),
  ('II', 33, '道に迷いました (Michi ni mayoimashita)', 33, false),
  ('II', 34, '病院に行ったほうがいいです (Byouin ni itta hou ga ii desu)', 34, false),
  ('II', 35, '予約をしてもいいですか (Yoyaku o shite mo ii desu ka)', 35, false),
  ('II', 36, '旅行の準備をしています (Ryokou no junbi o shite imasu)', 36, false),
  ('II', 37, '日本にいる間に (Nihon ni iru aida ni)', 37, false),
  ('II', 38, 'アルバイトを探しています (Arubaito o sagashite imasu)', 38, false),
  ('II', 39, 'インターネットで調べました (Inta-netto de shirabemashita)', 39, false),
  ('II', 40, '新聞を読んでいます (Shinbun o yonde imasu)', 40, false),
  ('II', 41, '意見を聞かせてください (Iken o kikasete kudasai)', 41, false),
  ('II', 42, '天気予報を見ましたか (Tenki yohou o mimashita ka)', 42, false),
  ('II', 43, 'お世話になりました (Osewa ni narimashita)', 43, false),
  ('II', 44, 'これは私が作ったものです (Kore wa watashi ga tsukutta mono desu)', 44, false),
  ('II', 45, '日本語が上手になりましたね (Nihongo ga jouzu ni narimashita ne)', 45, false),
  ('II', 46, 'おかげさまで (Okagesama de)', 46, false),
  ('II', 47, '留学したいです (Ryuugaku shitai desu)', 47, false),
  ('II', 48, 'お元気で (Ogenki de)', 48, false),
  ('II', 49, 'これからもよろしく (Korekara mo yoroshiku)', 49, false),
  ('II', 50, '勉強を続けます (Benkyou o tsuzukemasu)', 50, false)
ON CONFLICT (book, nomor_pelajaran) DO NOTHING;
