-- Batch 1: Susun Kalimat Bab 1-10 (8 soal each, strict MNN curriculum)

DELETE FROM quiz_questions WHERE lesson_id BETWEEN 1 AND 10 AND jenis_soal = 'susun_kalimat';

INSERT INTO quiz_questions (lesson_id, jenis_soal, soal, pilihan_jawaban, jawaban_benar) VALUES
  (1, 'susun_kalimat', 'Saya adalah siswa.', '["わたし", "は", "がくせい", "です", "。"]', 'わたしはがくせいです。'),
  (1, 'susun_kalimat', 'Apakah Anda seorang guru?', '["あなた", "は", "せんせい", "です", "か", "？"]', 'あなたはせんせいですか？'),
  (1, 'susun_kalimat', 'Saudara Santos bukan pegawai perusahaan.', '["サントス", "さん", "は", "かいしゃいん", "じゃ", "ありません", "。"]', 'サントスさんはかいしゃいんじゃありません。'),
  (1, 'susun_kalimat', 'Tuan Miller adalah orang Amerika.', '["ミラー", "さん", "は", "アメリカ", "じん", "です", "。"]', 'ミラーさんはアメリカじんです。'),
  (1, 'susun_kalimat', 'Saudara Gupta juga seorang dokter.', '["グプタ", "さん", "も", "いしゃ", "です", "。"]', 'グプタさんもいしゃです。'),
  (1, 'susun_kalimat', 'Siapakah orang itu?', '["あの", "ひと", "は", "だれ", "です", "か", "？"]', 'あのひとはだれですか？'),
  (1, 'susun_kalimat', 'Umur berapakah Saudara Teresa?', '["テレサ", "ちゃん", "は", "なんさい", "です", "か", "？"]', 'テレサちゃんはなんさいですか？'),
  (1, 'susun_kalimat', 'Saudara Karina juga mahasiswa Universitas Fuji.', '["カリナ", "さん", "も", "ふじ", "だいがく", "の", "がくせい", "です", "。"]', 'カリナさんもふじだいがくのがくせいです。'),
  (2, 'susun_kalimat', 'Ini adalah buku kamus.', '["これ", "は", "じしょ", "です", "。"]', 'これはじしょです。'),
  (2, 'susun_kalimat', 'Apakah itu sebuah buku catatan?', '["それ", "は", "のーと", "です", "か", "？"]', 'それはのーとですか？'),
  (2, 'susun_kalimat', 'Apakah benda yang di sebelah sana itu?', '["あれ", "は", "なん", "です", "か", "？"]', 'あれはなんですか？'),
  (2, 'susun_kalimat', 'Payung ini adalah milik saya.', '["この", "かさ", "は", "わたし", "の", "です", "。"]', 'このかさはわたしのです。'),
  (2, 'susun_kalimat', 'Ini bukan majalah mobil.', '["これ", "は", "くるま", "の", "ざっし", "じゃ", "ありません", "。"]', 'これはくるまのざっしじゃありません。'),
  (2, 'susun_kalimat', 'Gantungan kunci itu milik siapa?', '["その", "かぎ", "は", "だれ", "の", "です", "か", "？"]', 'そのかぎはだれのですか？'),
  (2, 'susun_kalimat', 'Ini adalah kartu nama saya.', '["これ", "は", "わたし", "の", "めいし", "です", "。"]', 'これはわたしのめいしです。'),
  (2, 'susun_kalimat', 'Buku ini bukan milik saya, tetapi milik Tuan Miller.', '["この", "ほん", "は", "わたし", "の", "じゃ", "ありません", "、", "ミラー", "さん", "の", "です", "。"]', 'このほんはわたしのじゃありません、ミラーさんのです。'),
  (3, 'susun_kalimat', 'Di sini adalah ruang kelas.', '["ここ", "は", "きょうしつ", "です", "。"]', 'ここはきょうしつです。'),
  (3, 'susun_kalimat', 'Toilet ada di sebelah sana.', '["おてあらい", "は", "あそこ", "です", "。"]', 'おてあらいはあそこです。'),
  (3, 'susun_kalimat', 'Di mana tempat resepsionis?', '["うけつけ", "は", "どこ", "です", "か", "？"]', 'うけつけはどこですか？'),
  (3, 'susun_kalimat', 'Kantor ada di arah sebelah sini.', '["じむしょ", "は", "こちら", "です", "。"]', 'じむしょはこちらです。'),
  (3, 'susun_kalimat', 'Tuan Miller ada di ruang rapat.', '["ミラー", "さん", "は", "かいぎしつ", "です", "。"]', 'ミラーさんはかいぎしつです。'),
  (3, 'susun_kalimat', 'Lift ada di mana?', '["エレベーター", "は", "どこ", "です", "か", "？"]', 'エレベーターはどこですか？'),
  (3, 'susun_kalimat', 'Sepatu ini buatan Italia.', '["この", "くつ", "は", "イタリア", "の", "です", "。"]', 'このくつはイタリアのです。'),
  (3, 'susun_kalimat', 'Jam tangan ini harganya 10.000 yen.', '["この", "とけい", "は", "いちまん", "えん", "です", "。"]', 'このとけいはいちまんえんです。'),
  (4, 'susun_kalimat', 'Sekarang jam 4 lewat 30 menit.', '["いま", "よじ", "はん", "です", "。"]', 'いまよじはんです。'),
  (4, 'susun_kalimat', 'Bank buka dari jam 9.', '["ぎんこう", "は", "くじ", "から", "です", "。"]', 'ぎんこうはくじからです。'),
  (4, 'susun_kalimat', 'Kantor pos tutup sampai jam 5.', '["ゆうびんきょく", "は", "ごじ", "まで", "です", "。"]', 'ゆうびんきょくはごじまでです。'),
  (4, 'susun_kalimat', 'Saya bekerja dari jam 8 sampai jam 5.', '["わたし", "は", "はちじ", "から", "ごじ", "まで", "はたらきます", "。"]', 'わたしははちじからごじまではたらきます。'),
  (4, 'susun_kalimat', 'Saya belajar setiap pagi.', '["わたし", "は", "まいあさ", "べんきょうします", "。"]', 'わたしはまいあさべんきょうします。'),
  (4, 'susun_kalimat', 'Apakah perpustakaan libur pada hari Sabtu?', '["としょかん", "は", "どようび", "に", "やすみ", "です", "か", "？"]', 'としょかんはどようびにやすみですか？'),
  (4, 'susun_kalimat', 'Kemarin saya sudah belajar.', '["きのう", "わたし", "は", "べんきょうしました", "。"]', 'きのうわたしはべんきょうしました。'),
  (4, 'susun_kalimat', 'Hari ini adalah hari Rabu.', '["きょう", "は", "すいようび", "です", "。"]', 'きょうはすいようびです。'),
  (5, 'susun_kalimat', 'Saya pergi ke sekolah.', '["わたし", "は", "がっこう", "へ", "いきます", "。"]', 'わたしはがっこうへいきます。'),
  (5, 'susun_kalimat', 'Saya pulang ke rumah dengan taksi.', '["たくしー", "で", "うち", "へ", "かえります", "。"]', 'たくしーでうちへかえります。'),
  (5, 'susun_kalimat', 'Saya datang ke Jepang bersama keluarga.', '["かぞく", "と", "にほん", "へ", "きました", "。"]', 'かぞくとにほんへきました。'),
  (5, 'susun_kalimat', 'Kapan Anda pergi ke Tokyo?', '["いつ", "とうきょう", "へ", "いきます", "か", "？"]', 'いつとうきょうへいきますか？'),
  (5, 'susun_kalimat', 'Saya pergi ke stasiun sendirian.', '["ひとり", "で", "えき", "へ", "いきます", "。"]', 'ひとりでえきへいきます。'),
  (5, 'susun_kalimat', 'Kereta cepat (Shinkansen) pergi ke Osaka.', '["しんかんせん", "は", "おおさか", "へ", "いきます", "。"]', 'しんかんせんはおおさかへいきます。'),
  (5, 'susun_kalimat', 'Bulan depan saya akan pulang ke negara asal.', '["らいげつ", "くに", "へ", "かえります", "。"]', 'らいげつくにへかえります。'),
  (5, 'susun_kalimat', 'Kemarin dulu saya pergi ke supermarket.', '["おととい", "すーぱー", "へ", "いきました", "。"]', 'おとといすーぱーへいきました。'),
  (6, 'susun_kalimat', 'Saya makan nasi.', '["わたし", "は", "ごはん", "を", "たべます", "。"]', 'わたしはごはんをたべます。'),
  (6, 'susun_kalimat', 'Saya membeli koran di stasiun.', '["えき", "で", "しんぶん", "を", "かいました", "。"]', 'えきでしんぶんをかいました。'),
  (6, 'susun_kalimat', 'Mau makan bersama-sama?', '["いっしょに", "ごはん", "を", "たべませんか", "？"]', 'いっしょにごはんをたべませんか？'),
  (6, 'susun_kalimat', 'Mari minum bir di restoran.', '["れすとらん", "で", "びーる", "を", "のみましょう", "。"]', 'れすとらんでびーるをのみましょう。'),
  (6, 'susun_kalimat', 'Setiap malam saya menonton video.', '["まいばん", "びでお", "を", "みます", "。"]', 'まいばんびでおをみます。'),
  (6, 'susun_kalimat', 'Hari ini saya tidak minum apa-apa.', '["きょう", "は", "なに", "も", "のみません", "。"]', 'きょうはなにものみません。'),
  (6, 'susun_kalimat', 'Saya bertemu dengan teman di kebun.', '["にわ", "で", "ともだち", "に", "あいます", "。"]', 'にわでともだちにあいます。'),
  (6, 'susun_kalimat', 'Saya membeli jus dan buah-buahan.', '["じゅーす", "と", "くだもの", "を", "かいました", "。"]', 'じゅーすとくだものをかいました。'),
  (7, 'susun_kalimat', 'Saya makan makan malam dengan sumpit.', '["はし", "で", "ばんごはん", "を", "たべます", "。"]', 'はしでばんごはんをたべます。'),
  (7, 'susun_kalimat', 'Saya menulis laporan dalam bahasa Jepang.', '["にほんご", "で", "れぽーと", "を", "かきます", "。"]', 'にほんごでれぽーとをかきます。'),
  (7, 'susun_kalimat', 'Saya memberikan kado kepada Ibu.', '["はは", "に", "ぷれぜんと", "を", "あげます", "。"]', 'ははにぷれぜんとをあげます。'),
  (7, 'susun_kalimat', 'Saya telah menerima tiket dari Tuan Miller.', '["ミラー", "さん", "に", "きっぷ", "を", "もらいました", "。"]', 'ミラーさんにきっぷをもらいました。'),
  (7, 'susun_kalimat', 'Saya meminjamkan uang kepada teman.', '["ともだち", "に", "おかね", "を", "かします", "。"]', 'ともだちにおかねをかします。'),
  (7, 'susun_kalimat', 'Apakah Anda sudah mengirim email?', '["もう", "めーる", "を", "おくりました", "か", "？"]', 'もうめーるをおくりましたか？'),
  (7, 'susun_kalimat', 'Tidak, belum (mengirim).', '["いいえ", "、", "まだ", "です", "。"]', 'いいえ、まだです。'),
  (7, 'susun_kalimat', 'Saya belajar bahasa Jepang dari guru.', '["せんせい", "に", "にほんご", "を", "ならいます", "。"]', 'せんせいににほんごをならいます。'),
  (8, 'susun_kalimat', 'Kyoto adalah kota yang indah.', '["きょうと", "は", "きれい", "な", "まち", "です", "。"]', 'きょうとはきれいなまちです。'),
  (8, 'susun_kalimat', 'Gunung Fuji sangat tinggi.', '["ふじさん", "は", "とても", "たかい", "です", "。"]', 'ふじさんはとてもたかいです。'),
  (8, 'susun_kalimat', 'Bahasa Jepang tidak begitu sulit.', '["にほんご", "は", "あまり", "むずかしくない", "です", "。"]', 'にほんごはあまりむずかしくないです。'),
  (8, 'susun_kalimat', 'Bagaimanakah kehidupan di Jepang?', '["にほん", "の", "せいかつ", "は", "どう", "です", "か", "？"]', 'にほんのせいかつはどうですか？'),
  (8, 'susun_kalimat', 'Makanan ini enak sekali.', '["この", "たべもの", "は", "とても", "おいしい", "です", "。"]', 'このたべものはとてもおいしいです。'),
  (8, 'susun_kalimat', 'Asrama ini tua tetapi bersih.', '["この", "りょう", "は", "ふるい", "です", "が", "、", "きれい", "です", "。"]', 'このりょうはふるいですが、きれいです。'),
  (8, 'susun_kalimat', 'Tuan Miller adalah orang yang ramah.', '["ミラー", "さん", "は", "しんせつ", "な", "ひと", "です", "。"]', 'ミラーさんはしんせつなひとです。'),
  (8, 'susun_kalimat', 'Hari ini saya senggang.', '["きょう", "わたし", "は", "ひま", "です", "。"]', 'きょうわたしはひまです。'),
  (9, 'susun_kalimat', 'Saya suka masakan Jepang.', '["わたし", "は", "にほん", "りょうり", "が", "すき", "です", "。"]', 'わたしはにほんりょうりがすきです。'),
  (9, 'susun_kalimat', 'Saya sedikit mengerti huruf Kanji.', '["かんじ", "が", "すこし", "わかります", "。"]', 'かんじがすこしわかります。'),
  (9, 'susun_kalimat', 'Tuan Miller pandai menari.', '["ミラー", "さん", "は", "だんす", "が", "じょうず", "です", "。"]', 'ミラーさんはだんすがじょうずです。'),
  (9, 'susun_kalimat', 'Karena tidak ada waktu, saya tidak membaca buku.', '["じかん", "が", "ありません", "から", "、", "ほん", "を", "よみません", "。"]', 'じかんがありませんから、ほんをよみません。'),
  (9, 'susun_kalimat', 'Mengapa Anda tidak membeli tiket?', '["どうして", "きっぷ", "を", "かいません", "か", "？"]', 'どうしてきっぷをかいませんか？'),
  (9, 'susun_kalimat', 'Saya mempunyai janji dengan teman.', '["ともだち", "と", "やくそく", "が", "あります", "。"]', 'ともだちとやくそくがあります。'),
  (9, 'susun_kalimat', 'Saya sama sekali tidak mengerti bahasa Inggris.', '["えいご", "が", "ぜんぜん", "わかりません", "。"]', 'えいごがぜんぜんわかりません。'),
  (9, 'susun_kalimat', 'Istri Tuan Santos tidak begitu menyukai olahraga.', '["サントス", "さん", "の", "おくさん", "は", "すぽーつ", "が", "あまり", "すき", "じゃ", "ありません", "。"]', 'サントスさんのおくさんはすぽーつがあまりすきじゃありません。'),
  (10, 'susun_kalimat', 'Ada komputer di atas meja.', '["つくえ", "の", "うえ", "に", "ぱそこん", "が", "あります", "。"]', 'つくえのうえにぱそこんがあります。'),
  (10, 'susun_kalimat', 'Ada Tuan Miller di dalam ruang kelas.', '["きょうしつ", "の", "なか", "に", "ミラー", "さん", "が", "います", "。"]', 'きょうしつのなかにミラーさんがいます。'),
  (10, 'susun_kalimat', 'Di manakah kucing itu berada?', '["ねこ", "は", "どこ", "に", "います", "か", "？"]', 'ねこはどこにいますか？'),
  (10, 'susun_kalimat', 'Toko buku ada di antara kedai kopi dan bank.', '["ほんや", "は", "きっさてん", "と", "ぎんこう", "の", "あいだ", "に", "あります", "。"]', 'ほんやはきっさてんとぎんこうのあいだにあります。'),
  (10, 'susun_kalimat', 'Ada berbagai macam barang di dalam kotak.', '["はこ", "の", "なか", "に", "いろいろ", "な", "もの", "が", "あります", "。"]', 'はこのなかにいろいろなものがあります。'),
  (10, 'susun_kalimat', 'Ada seekor anjing di dekat pintu.', '["どあ", "の", "ちかく", "に", "いぬ", "が", "います", "。"]', 'どあのちかくにいぬがいます。'),
  (10, 'susun_kalimat', 'Di bawah tempat tidur tidak ada apa-apa.', '["べっど", "の", "した", "に", "なに", "も", "ありません", "。"]', 'べっどのしたになにもありません。'),
  (10, 'susun_kalimat', 'Tempat naik bus (halte) ada di depan gedung.', '["ばす", "のりば", "は", "びる", "の", "まえ", "に", "あります", "。"]', 'ばすのりばはびるのまえにあります。');