INSERT INTO kotoba (lesson_id, kata_jepang, romaji, arti_indonesia) VALUES
(1, 'わたし', 'watashi', 'saya'),
(1, 'あなた', 'anata', 'kamu'),
(1, 'せんせい', 'sensei', 'guru'),
(1, 'がくせい', 'gakusei', 'mahasiswa'),
(1, 'かいしゃいん', 'kaishain', 'karyawan'),
(1, 'にほんじん', 'nihonjin', 'orang Jepang'),
(1, 'がいこくじん', 'gaikokujin', 'orang asing'),
(1, 'せいと', 'seito', 'murid'),
(1, 'だいがく', 'daigaku', 'universitas'),
(1, 'ともだち', 'tomodachi', 'teman'),
(2, 'これ', 'kore', 'ini'),
(2, 'それ', 'sore', 'itu'),
(2, 'あれ', 'are', 'itu (jauh)'),
(2, 'この', 'kono', 'ini ~'),
(2, 'その', 'sono', 'itu ~'),
(2, 'あの', 'ano', 'itu ~ (jauh)'),
(2, 'ペン', 'pen', 'pulpen'),
(2, 'ほん', 'hon', 'buku'),
(2, 'かばん', 'kaban', 'tas'),
(2, 'つくえ', 'tsukue', 'meja'),
(2, 'いす', 'isu', 'kursi'),
(2, 'まど', 'mado', 'jendela'),
(3, 'いくら', 'ikura', 'berapa'),
(3, 'ください', 'kudasai', 'tolong'),
(3, 'おかね', 'okane', 'uang'),
(3, 'たかい', 'takai', 'mahal'),
(3, 'やすい', 'yasui', 'murah'),
(3, 'みせ', 'mise', 'toko'),
(3, 'レストラン', 'resutoran', 'restoran'),
(3, 'メニュー', 'menyuu', 'menu'),
(3, 'みず', 'mizu', 'air'),
(3, 'おちゃ', 'ocha', 'teh'),
(3, 'コーヒー', 'koohii', 'kopi'),
(4, 'でんしゃ', 'densha', 'kereta'),
(4, 'バス', 'basu', 'bus'),
(4, 'タクシー', 'takushii', 'taksi'),
(4, 'くうこう', 'kuukou', 'bandara'),
(4, 'えき', 'eki', 'stasiun'),
(5, 'びょういん', 'byouin', 'rumah sakit'),
(5, 'こうばん', 'kouban', 'pos polisi'),
(5, 'ぎんこう', 'ginkou', 'bank'),
(5, 'ゆうびんきょく', 'yuubinkyoku', 'kantor pos'),
(5, 'としょかん', 'toshokan', 'perpustakaan'),
(6, 'コンビニ', 'konbini', 'minimarket'),
(6, 'スーパー', 'suupaa', 'supermarket'),
(6, 'こうえん', 'kouen', 'taman'),
(6, 'はくぶつかん', 'hakubutsukan', 'museum'),
(6, 'おてら', 'otera', 'kuil'),
(7, 'いぬ', 'inu', 'anjing'),
(7, 'ねこ', 'neko', 'kucing'),
(7, 'とり', 'tori', 'burung'),
(7, 'うま', 'uma', 'kuda'),
(7, 'うし', 'ushi', 'sapi'),
(8, 'あか', 'aka', 'merah'),
(8, 'あお', 'ao', 'biru'),
(8, 'きいろ', 'kiiro', 'kuning'),
(8, 'みどり', 'midori', 'hijau'),
(8, 'くろ', 'kuro', 'hitam'),
(8, 'しろ', 'shiro', 'putih'),
(9, 'おおきい', 'ookii', 'besar'),
(9, 'ちいさい', 'chiisai', 'kecil'),
(9, 'あたらしい', 'atarashii', 'baru'),
(9, 'ふるい', 'furui', 'tua'),
(9, 'いい', 'ii', 'baik'),
(9, 'わるい', 'warui', 'buruk'),
(10, 'あつい', 'atsui', 'panas'),
(10, 'さむい', 'samui', 'dingin'),
(10, 'つめたい', 'tsumetai', 'dingin (benda)'),
(10, 'むずかしい', 'muzukashii', 'susah'),
(10, 'やさしい', 'yasashii', 'mudah'),
(11, 'おもしろい', 'omoshiroi', 'menarik'),
(11, 'つまらない', 'tsumaranai', 'membosankan'),
(11, 'いそがしい', 'isogashii', 'sibuk'),
(11, 'げんき', 'genki', 'sehat'),
(11, 'しんぱい', 'shinpai', 'khawatir'),
(12, 'いえ', 'ie', 'rumah'),
(12, 'へや', 'heya', 'kamar'),
(12, 'にわ', 'niwa', 'halaman'),
(12, 'でんわ', 'denwa', 'telepon'),
(12, 'とけい', 'tokei', 'jam'),
(12, 'かさ', 'kasa', 'payung'),
(13, 'くつ', 'kutsu', 'sepatu'),
(13, 'ぼうし', 'boushi', 'topi'),
(13, 'ふく', 'fuku', 'baju'),
(13, 'しんぶん', 'shinbun', 'koran'),
(13, 'じてんしゃ', 'jitensha', 'sepeda'),
(14, 'たべる', 'taberu', 'makan'),
(14, 'のむ', 'nomu', 'minum'),
(14, 'いく', 'iku', 'pergi'),
(14, 'くる', 'kuru', 'datang'),
(14, 'かえる', 'kaeru', 'pulang'),
(14, 'あるく', 'araku', 'berjalan'),
(15, 'はなす', 'hanasu', 'bicara'),
(15, 'きく', 'kiku', 'dengar'),
(15, 'みる', 'miru', 'lihat'),
(15, 'よむ', 'yomu', 'baca'),
(15, 'かく', 'kaku', 'tulis'),
(15, 'つかう', 'tsukau', 'pakai'),
(16, 'つくる', 'tsukuru', 'buat'),
(16, 'うる', 'uru', 'jual'),
(16, 'かう', 'kau', 'beli'),
(16, 'おしえる', 'oshieru', 'ajar'),
(16, 'ならう', 'narau', 'belajar'),
(16, 'わかる', 'wakaru', 'mengerti'),
(17, 'しごと', 'shigoto', 'kerja'),
(17, 'かいもの', 'kaimono', 'belanja'),
(17, 'りょうり', 'ryouri', 'masak'),
(17, 'せんたく', 'sentaku', 'cuci'),
(17, 'そうじ', 'souji', 'bersih'),
(17, 'うんどう', 'undou', 'olahraga'),
(18, 'さんぽ', 'sanpo', 'jalan'),
(18, 'りょこう', 'ryokou', 'travel'),
(18, 'しゅくだい', 'shukudai', 'PR'),
(18, 'べんきょう', 'benkyou', 'belajar'),
(18, 'はしる', 'hashiru', 'lari'),
(19, 'はやい', 'hayai', 'cepat'),
(19, 'おそい', 'osoi', 'lambat'),
(19, 'ちかい', 'chikai', 'dekat'),
(19, 'とおい', 'tooi', 'jauh'),
(19, 'おもい', 'omoi', 'berat'),
(19, 'かるい', 'karui', 'ringan'),
(20, 'あそこ', 'asoko', 'situ'),
(20, 'となり', 'tonari', 'sebelah'),
(20, 'そば', 'soba', 'dekat'),
(20, 'まえ', 'mae', 'depan'),
(20, 'うしろ', 'ushiro', 'belakang'),
(21, 'みぎ', 'migi', 'kanan'),
(21, 'ひだり', 'hidari', 'kiri'),
(21, 'なか', 'naka', 'dalam'),
(21, 'うえ', 'ue', 'atas'),
(21, 'した', 'shita', 'bawah'),
(21, 'ちかく', 'chikaku', 'sekitar'),
(22, 'あめ', 'ame', 'hujan'),
(22, 'くも', 'kumo', 'awan'),
(22, 'かぜ', 'kaze', 'angin'),
(22, 'ゆき', 'yuki', 'salju'),
(22, 'そら', 'sora', 'langit'),
(23, 'はる', 'haru', 'musim semi'),
(23, 'なつ', 'natsu', 'musim panas'),
(23, 'あき', 'aki', 'musim gugur'),
(23, 'ふゆ', 'fuyu', 'musim dingin'),
(23, 'てんき', 'tenki', 'cuaca'),
(24, 'びじゅつかん', 'bijutsukan', 'museum seni'),
(24, 'としょかん', 'toshokan', 'perpustakaan'),
(24, 'びょういん', 'byouin', 'rumah sakit'),
(24, 'くすり', 'kusuri', 'obat'),
(25, 'きって', 'kitte', 'perangko'),
(25, 'はがき', 'hagaki', 'kartu pos'),
(25, 'てがみ', 'tegami', 'surat'),
(25, 'にもつ', 'nimotsu', 'barang bawaan'),
(25, 'はこ', 'hako', 'kotak'),
(26, 'おひさしぶり', 'ohisashiburi', 'lama tak jumpa'),
(26, 'かしこまりました', 'kashikomarimashita', 'siap'),
(26, 'ざんねん', 'zannen', 'sayang'),
(26, 'しつれい', 'shitsurei', 'permisi'),
(27, 'うかがう', 'ukagau', 'kunjungi'),
(27, 'もうしこむ', 'moushikomu', 'daftar'),
(27, 'けっこう', 'kekkou', 'cukup'),
(27, 'どうぞよろしく', 'douzo yoroshiku', 'senang berkenalan'),
(28, 'あさごはん', 'asagohan', 'sarapan'),
(28, 'ひるごはん', 'hirugohan', 'makan siang'),
(28, 'ばんごはん', 'bangohan', 'makan malam'),
(28, 'くだもの', 'kudamono', 'buah'),
(29, 'ぎゅうにゅう', 'gyuunyuu', 'susu'),
(29, 'パン', 'pan', 'roti'),
(29, 'たまご', 'tamago', 'telur'),
(29, 'さとう', 'satou', 'gula'),
(29, 'しお', 'shio', 'garam'),
(29, 'しょうゆ', 'shouyu', 'kecap'),
(30, 'ごはん', 'gohan', 'nasi'),
(30, 'みそ', 'miso', 'miso'),
(30, 'やさい', 'yasai', 'sayur'),
(30, 'くだもの', 'kudamono', 'buah'),
(30, 'さかな', 'sakana', 'ikan'),
(30, 'にく', 'niku', 'daging'),
(31, 'はな', 'hana', 'bunga'),
(31, 'き', 'ki', 'pohon'),
(31, 'くさ', 'kusa', 'rumput'),
(31, 'つち', 'tsuchi', 'tanah'),
(31, 'にじ', 'niji', 'pelangi'),
(31, 'かみなり', 'kaminari', 'petir'),
(32, 'むらさき', 'murasaki', 'ungu'),
(32, 'ちゃいろ', 'chairo', 'coklat'),
(32, 'はいいろ', 'haiiro', 'abu-abu'),
(32, 'ももいろ', 'momoiro', 'merah muda'),
(32, 'だいだいいろ', 'daidaiiro', 'oranye'),
(33, 'いっしょに', 'issho ni', 'bersama'),
(33, 'ひとりで', 'hitori de', 'sendiri'),
(33, 'いつも', 'itsumo', 'selalu'),
(33, 'ときどき', 'tokidoki', 'kadang'),
(33, 'たいてい', 'taitei', 'biasanya'),
(34, 'ぜんぜん', 'zenzen', 'sama sekali'),
(34, 'あまり', 'amari', 'tidak begitu'),
(34, 'だんだん', 'dandan', 'perlahan'),
(34, 'もう', 'mou', 'sudah'),
(34, 'まだ', 'mada', 'belum'),
(35, 'すこし', 'sukoshi', 'sedikit'),
(35, 'たくさん', 'takusan', 'banyak'),
(35, 'おおい', 'ooi', 'banyak jumlah'),
(35, 'すくない', 'sukunai', 'sedikit jumlah'),
(36, 'やおや', 'yaoya', 'toko sayur'),
(36, 'さかなや', 'sakanaya', 'toko ikan'),
(36, 'ほんや', 'honya', 'toko buku'),
(36, 'くすりや', 'kusuriya', 'apotek'),
(36, 'はなや', 'hanaya', 'toko bunga'),
(37, 'でぱーと', 'depaato', 'department store'),
(37, 'せんもんてん', 'senmonten', 'toko khusus'),
(37, 'うりば', 'uriba', 'lantai penjualan'),
(37, 'かいだん', 'kaidan', 'tangga'),
(37, 'エスカレーター', 'esukareetaa', 'eskalator'),
(38, 'きっぷ', 'kippu', 'karcis'),
(38, 'きせん', 'kisen', 'karcis (harian)'),
(38, 'こうくうびん', 'koukuubin', 'pos udara'),
(38, 'ふなびん', 'funabin', 'pos laut'),
(38, 'そくたつ', 'sokutatsu', 'pos kilat'),
(39, 'インターネット', 'intaanetto', 'internet'),
(39, 'メール', 'meeru', 'email'),
(39, 'パソコン', 'pasokon', 'komputer'),
(39, 'プリンター', 'purintaa', 'printer'),
(40, 'しんぶん', 'shinbun', 'koran'),
(40, 'ざっし', 'zasshi', 'majalah'),
(40, 'にっき', 'nikki', 'buku harian'),
(40, 'ちず', 'chizu', 'peta'),
(40, 'じてん', 'jiten', 'kamus'),
(41, 'いけん', 'iken', 'pendapat'),
(41, 'はんたい', 'hantai', 'lawan/berlawanan'),
(41, 'さんせい', 'sansei', 'setuju'),
(41, 'けっか', 'kekka', 'hasil'),
(41, 'りゆう', 'riyuu', 'alasan'),
(42, 'てんきよほう', 'tenki yohou', 'ramalan cuaca'),
(42, 'きおん', 'kion', 'suhu udara'),
(42, 'しつど', 'shitsudo', 'kelembaban'),
(42, 'たいふう', 'taifuu', 'topan'),
(42, 'じしん', 'jishin', 'gempa'),
(43, 'おせわになりました', 'osewa ni narimashita', 'terima kasih (perpisahan)'),
(43, 'おかげさまで', 'okagesama de', 'berkat doa Anda'),
(43, 'おげんきで', 'ogenki de', 'semoga sehat'),
(43, 'さようなら', 'sayounara', 'selamat tinggal'),
(44, 'つづける', 'tsudukeru', 'melanjutkan'),
(44, 'おわる', 'owaru', 'berakhir'),
(44, 'はじめる', 'hajimeru', 'memulai'),
(44, 'けってい', 'kettei', 'keputusan'),
(45, 'じょうず', 'jouzu', 'pandai'),
(45, 'へた', 'heta', 'tidak pandai'),
(45, 'とくい', 'tokui', 'jago'),
(45, 'にがて', 'nigate', 'lemah'),
(45, 'すき', 'suki', 'suka'),
(45, 'きらい', 'kirai', 'tidak suka'),
(46, 'ゆめ', 'yume', 'mimpi'),
(46, 'しょうらい', 'shourai', 'masa depan'),
(46, 'けいけん', 'keiken', 'pengalaman'),
(46, 'ぼうけん', 'bouken', 'petualangan'),
(46, 'せいこう', 'seikou', 'sukses'),
(47, 'りゅうがく', 'ryuugaku', 'studi ke luar negeri'),
(47, 'こうりゅう', 'kouryuu', 'pertukaran'),
(47, 'けんきゅう', 'kenkyuu', 'penelitian'),
(47, 'はっぴょう', 'happyyou', 'presentasi'),
(48, 'かぞく', 'kazoku', 'keluarga'),
(48, 'りょうしん', 'ryoushin', 'orang tua'),
(48, 'きょうだい', 'kyoudai', 'saudara'),
(48, 'こども', 'kodomo', 'anak'),
(48, 'おっと', 'otto', 'suami'),
(48, 'つま', 'tsuma', 'istri'),
(49, 'しんせき', 'shinseki', 'kerabat'),
(49, 'となりのひと', 'tonari no hito', 'tetangga'),
(49, 'なかま', 'nakama', 'rekan'),
(49, 'しどう', 'shidou', 'bimbingan'),
(50, 'つづける', 'tsuzukeru', 'melanjutkan'),
(50, 'がんばる', 'ganbaru', 'berusaha keras'),
(50, 'まなぶ', 'manabu', 'belajar (formal)'),
(50, 'みにつける', 'mi ni tsukeru', 'menguasai')
ON CONFLICT (lesson_id, kata_jepang) DO NOTHING;